### ISSUE TITLE
Zabbix Agent is not responding after upgrade to Zabbix 4.0

### ISSUE THREAD

**Issue by mbleonardo** [jitlogic/zorka#192]
Hello!

We've got a problem with Zorka after upgrading to Zabbix 4.0:

```
# zabbix_get -s SERVER -p 10055 -k 'zorka.jmx["java","java.lang:type=Runtime","Uptime"]'
zabbix_get [16172]: Timeout while executing operation
```

But, with telnet, it works:

```
#telnet SERVER 10055
Trying 10.70.2.24...
Connected to SERVER.
Escape character is '^]'.
zorka.jmx["java","java.lang:type=Runtime","Uptime"]
ZBXD33784774Connection closed by foreign host.
```
The same happens with Zorka Dev. version (1.90.4).

I think this might be a bug related to this:

> Support for the plain text protocol has been dropped and a header  is now mandatory. A header has been added to Zabbix get requests,  Zabbix server/proxy passive check requests and frontend requests to  Zabbix server.    As a consequence, Zabbix agents that are older than version 1.4 are no  longer supported. Also, messages from self-written senders will be  rejected if the header is absent. Whereas previously Zabbix trappers  would accept messages without headers as well as messages with headers,  now they will only accept messages with protocol header.     

https://www.zabbix.com/documentation/current/manual/installation/upgrade_notes_400

If it's not a bug, I would appreciate any help on debugging/solving this.

Thank you!

**Comment by jitlogic** [comment]
Zorka is using plaintext at this moment. There is preliminary TLS support implemented but not tested at all. I'll try this with Zabbix 4.0 and let you know in a few days.

**Comment by jitlogic** [comment]
Fixed in both master and v1-stable branches. Please fetch and compile branch you're interested in. Note that compiling v1-stable requires JDK6.

**Comment by kkmaslowski** [comment]
@jitlogic I updated zorka to 1.0.17 and I still have the same problem (Timeout). Should I compile it from sources?

**Comment by jitlogic** [comment]
Yes, forgot to mention, sorry. Stable branch (1.0.18-SNAPSHOT) needs to be compiled. Development branch has been released meanwhile, so it is available in 1.90.6.
